chrispinkney/cinesync

.github/pull_request_template.md
Implements a simple PR template file.
=> chore(github): Implement PR template file

web/src/app/about/page.tsx, web/src/app/layout.tsx, web/src/components/Footer/Footer.tsx
Closes #9, #10 
I've added some content to the about page about the app.
I also removed the Footer component since I don't think we really need it- we don't really have anything to show on a footer, do we? I was racking my brain trying to come up with stuff to put on it and couldn't think of any so I just removed it for now. We can also readd it later, or I can simply add it back to this PR. LMK.
`git fetch --all`
`git switch about`
start db, api, and web, navigate to `localhost:7000/about`
OR
Navigate to the [preview](https://cinesync-git-about-chrispinkney.vercel.app/about) link.
=> Add about page, remove footer

api/package.json, api/prisma/migrations/20231013111556_/migration.sql, api/prisma/schema.prisma, api/src/guards/admin.guard.ts, api/src/lists/lists.controller.ts, api/src/lists/lists.service.ts, api/src/users/auth.service.spec.ts, api/src/users/dtos/user.dto.ts, api/src/users/users.controller.spec.ts, api/src/users/users.controller.ts, api/src/users/users.service.ts
Closes #33 
Instead of using `number` for `userId` I changed the backend to use uuid's instead. There's a lot of changes in this pr but the actual change is essentially two lines in the schema file and the resulting changes from number type to string.
`git fetch --all`
`git switch issue-33`
`cd api`
`npm i`
`docker-compose up --build db`
`npx prisma migrate dev` is required here due to changes to the schema
`npm run dev`
App should function as normal, feel free to test any aspect.
=> chore(api): change userId to uuid

api/src/app.module.ts, api/src/dao/list.dao.ts, api/src/dao/user.dao.ts, api/src/email/email.service.ts, api/src/lists/dtos/create-list-return.dto.ts, api/src/lists/dtos/update-list-privacy.dto.ts, api/src/lists/interceptors/remove-list-create-fields.interceptor.ts, api/src/lists/lists.controller.ts, api/src/lists/lists.module.ts, api/src/lists/lists.service.ts, api/src/users/auth.service.spec.ts, api/src/users/auth.service.ts, api/src/users/users.controller.spec.ts, api/src/users/users.controller.ts, api/src/users/users.module.ts, api/src/users/users.service.spec.ts, api/src/users/users.service.ts, api/test/auth.e2e-spec.ts
Closes #29
This PR changes how the services communicate with prisma. Instead of talking directly to prisma both the user and list service now communicate via `dao` files.
Run the project as normal, no functionality should have been impacted.
=> Refactor user/list service code to dao

api/src/dao/list.dao.ts, api/src/dao/user.dao.ts, api/src/guards/list.guard.ts, api/src/lists/lists.controller.ts, api/src/lists/lists.service.ts, api/src/main.ts, api/src/prisma/filter/prisma-client-exception.filter.ts, api/src/users/auth.service.spec.ts, api/src/users/auth.service.ts, api/src/users/middlewares/current-user.middleware.ts, api/src/users/users.controller.spec.ts, api/src/users/users.service.ts, api/src/utils/logLevels.ts
Closes #17
This PR refactors a lot of the backend code to use a prisma error filter instead of relying on throwing or console errors. As a result we no longer have to do a lot of checking with code since primsa now throws a proper error.
I've also changed share/unshare to be toggleable and have removed the `shareById` route.
Run the app and test as normal.
=> refactor(api): refactor api to implement prisma error handler

api/src/lists/lists.controller.ts, api/src/users/users.controller.ts, api/test/auth.e2e-spec.ts
Closes #26
This PR updates certain http status codes where applicable.
Run the app as normal and the respective status codes should be displayed upon certain actions.
=> Issue 26: Update http status codes

api/src/users/users.controller.spec.ts, api/src/users/users.controller.ts, api/src/users/users.module.ts
Closes #46
When a user deletes their account, the lists were not deleted with them. Now they are.
1. Create a user
2. Create many lists
3. Delete the user
4. Lists should go poof
=> Issue-46: Cascade list upon user deletion

web/package.json, web/src/app/dashboard/(lists)/list/[slug]/page.tsx, web/src/app/dashboard/(lists)/lists/page.tsx, web/src/components/List/ListActions.tsx, web/src/components/List/ListCreation/ListCreationButton.tsx, web/src/components/List/ListCreation/ListCreationModal.tsx, web/src/components/List/ListDeleteConfirmationModal.tsx, web/src/components/List/ListGrid/ListCard.tsx, web/src/components/List/ListGrid/ListGrid.tsx, web/src/components/List/ListShareModal.tsx, web/src/components/List/MovieListTable/GenreDropdown.tsx, web/src/components/List/MovieListTable/MovieListTable.tsx, web/src/components/List/MovieListTable/MovieListTableContainer.tsx, web/src/components/List/MovieListTable/MovieListTableEditToolbar.tsx, web/src/context/lists.context.tsx, web/src/context/movielist.context.tsx, web/src/types.ts, web/theme/theme.ts
Fixes/Closes #11
This PR implements frontend functionality for the `/lists` api controller. Two pages have been added: `/lists` and `/list/:listId`.
- View lists in a card grid, with each list showing a preview of the list contents.
- Each list card has share and delete buttons that open a dialog, allowing the list to be shared by email or deleted.
- An "add list" button is available at the bottom right of the page, allowing the creation of new lists. In planned future changes, this will redirect to the new list upon creation success.
- Clicking on the list will open that list up in `/list/:listId`.
- A selected list will be displayed as a table, allowing for viewing and editing of the movies contained within that list.
- An "add movie" button is available in the table header to allow …
=> Issue-11: Implement List (main) page

web/src/components/Header/AvatarLogo.tsx, web/src/components/Header/Header.tsx
closes #74 
Moved the Avatar logo to a child component in order to make Header (parent) a server component.
- cd web
- npm run dev
=> refactor(web): Moved Avatar Logo menu to a child component

web/src/app/layout.tsx
Closes #12 
Adding meta tags allows the app to display correct titles in broswer tabs and where links are shared. Since the majority of the pages require `'use client'`, this has been implemented only into the top level `layout.tsx` file. However, title templating was added in case furuter implementation allows for metadata in page paths.
See [readme](https://github.com/chrispinkney/cinesync#running-cinesync)
=> Issue 12: Implement Meta Tags

api/prisma/migrations/20231018142046_/migration.sql, api/prisma/migrations/20231019005006_/migration.sql, api/prisma/schema.prisma, api/src/dao/list.dao.ts, api/src/email/email.service.ts, api/src/guards/list.guard.ts, api/src/lists/lists.controller.ts, api/src/lists/lists.service.ts, web/src/app/dashboard/(lists)/list/[slug]/page.tsx, web/src/components/List/ListActions.tsx, web/src/components/List/ListCreation/ListCreationModal.tsx, web/src/components/List/ListDeleteConfirmationModal.tsx, web/src/components/List/ListShareModal.tsx, web/src/context/movielist.context.tsx, web/src/types.ts
Closes #72
This PR changes the `listId` to use uuids instead of numbers.
Run the app and work through it e2e as normal, no functionality should have changed.
=> Issue-72: Use uuids for `listId`, `movieId`

api/src/dao/list.dao.ts, api/src/lists/dtos/create-list-return.dto.ts
Closes #58
This PR attaches the list creator to the list being returned to the frontend.
Create a list (optionally share it with another user as a sanity check and log in as the sharee) and get that list. The list should have (**only**) the creator attached to it.
=> Issue-58: Return list creator when fetching a list

api/package.json, api/prisma/migrations/20231019155434_/migration.sql, api/prisma/migrations/20231019182442_/migration.sql, api/prisma/schema.prisma, api/src/dao/user.dao.ts, api/src/users/users.controller.ts, api/src/users/users.service.ts
Closes #40 
This PR allows a user to upload their own avatar which stores it in the user table. It also allows a user to get their avatar, and delete their avatar.
Avatars currently must be of type [`image/jpeg`](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#jpeg_joint_photographic_experts_group_image) and <= 5MB in size.
Also, I edited the user route for getting a user by id (_which I don't think the frontend uses at all yet?_) to use a Query instead of a Param. Params are bullshit that should never be used.
Since the schema has changed the usual steps are required (see README.me):
1. `git switch main`
2. `git pull`
3. `git switch issue-40`
4. `cd api && npm i`
5. `npx prisma migrate dev`
6. `npm run db:generate`
I'll pass along an updated postman export for the …
=> Issue-40: Implement user avatar upload

api/src/users/auth.service.ts, api/src/users/users.controller.ts
No Issue
This PR fixes a bug in the user updating system. Now we ensure we properly encrypt the password before storing it.
`git switch main`
`git pull`
`git switch password-fix`
Run app as normal and try to update a user. See `PATCH update a specific user`.
=> Encrypt password before storing user

web/src/components/Login/AuthMain.tsx, web/src/components/Login/SignupCard.tsx
closes #2 Fix
This PR is a bug fix to display the LoginCard component when a user has successfully signed up.
- cd web
- npm i
- npm run dev
=> added change to login tab on successful signup

web/src/components/List/MovieListTable/MovieListTable.tsx
Fixes #71 
Previously new movies would be added to the bottom of the movie list, but when there are multiple pages of movies, the newly added movie is not visible, possibly causing confusion to the user.
This fix inserts the new movie at the beginning of the row array, rather than pushing it to the end.
=> fix(web): add new movie to top of movie list

README.md, api/package.json, api/prisma/migrations/20231022234349_/migration.sql, api/prisma/migrations/20231024014859_/migration.sql, api/prisma/schema.prisma, api/src/dao/user.dao.ts, api/src/lists/lists.controller.ts, api/src/lists/lists.module.ts, api/src/lists/lists.service.ts, api/src/users/users.controller.ts, api/src/users/users.service.ts
Closes #52
This PR adds the ability to implement friendships between users. Friendships can be one of three status': ` 'ACCEPT' | 'REJECT' | 'PENDING' | 'SENT'`.
- Users can get their friends/friend requests via: `GET {{BASE_URL}}/auth/friends`
- Users can send a friend request via: `POST {{BASE_URL}}/auth/friends/send`:
```json
{
"username": "chris"
}
```
- Users can update a friend request via: `POST {{BASE_URL}}/auth/friends/update`:
```json
{
"username": "chris",
"status": "ACCEPT"
}
```
- Users can reject a friend request (and delete a friendship) via: `POST {{BASE_URL}}/auth/friends/update`:
```json
{
"username": "chris",
"status": "REJECT"
}
```
Create several friends and try to create friend requests between them. Run the GET request during each step to see the potential status' …
=> Issue-52: Implement Friendship

api/prisma/migrations/20231023194423_/migration.sql, api/prisma/schema.prisma, api/src/dao/list.dao.ts, api/src/dao/user.dao.ts, api/src/guards/comment-auth.guard.ts, api/src/guards/list.guard.ts, api/src/lists/daos/comment.dao.ts, api/src/lists/dtos/comments.dto.ts, api/src/lists/dtos/create-comment.dto.ts, api/src/lists/dtos/create-list-return.dto.ts, api/src/lists/dtos/update-comment.dto.ts, api/src/lists/lists.controller.ts, api/src/lists/lists.module.ts, api/src/lists/lists.service.ts, api/src/users/users.module.ts, api/src/users/users.service.ts
Closes #55
This PR adds the ability to leave comments on a list.
This is currently draft as my brain hurts and I think other users can current edit/delete other people's comments, this should probably be fixed. I just wanted to push up what I had done already as it was getting chonky.
Pull, Switch, and run as normal. I'll pass along the postman file but the new routes are as follows:
1. `POST {{BASE_URL}}/lists/comments`
2. `PATCH {{BASE_URL}}/lists/comments/update`
3. `DELETE {{BASE_URL}}/lists/comments/delete`
4. `GET {{BASE_URL}}/lists/list?listId={{listId}}` <-- Augmented to show comments on a specific list
=> Issue-55: Add list comments

api/src/users/users.service.ts, web/src/app/dashboard/layout.tsx, web/src/app/dashboard/userprofile/page.tsx, web/src/components/Header/AvatarLogo.tsx, web/src/components/Header/Header.tsx, web/src/components/UserProfile/DeleteUserProfile.tsx, web/src/components/UserProfile/ProfileBottom.tsx, web/src/components/UserProfile/ProfileTop.tsx, web/src/components/UserProfile/UploadAvatarImage.tsx, web/src/components/UserProfile/UserProfileMain.tsx, web/src/context/user.context.tsx, web/src/utils/cinesync-api/fetch-user.ts
closes #3 
Adds user settings/profile page which implements:
- updating user details (username, email, password)
- account deleting
- uploading new avatar (need to revisit with backend changes)
- cd web
- npm i
- npm run dev
=> Issue-3: Implement user profile page

api/prisma/schema.prisma, api/src/lists/daos/list.dao.ts, api/src/lists/dtos/create-list-return.dto.ts, api/src/lists/dtos/create-list.dto.ts, api/src/lists/dtos/list.dto.ts, api/src/lists/dtos/movie.dto.ts, api/src/lists/dtos/update-list-privacy.dto.ts, api/src/lists/dtos/update-list.dto.ts, api/src/lists/guards/list.guard.ts, api/src/lists/lists.controller.ts, api/src/lists/lists.service.ts, api/src/users/auth/auth.service.spec.ts, api/src/users/auth/auth.service.ts, api/src/users/dtos/user.dto.ts, api/src/users/guards/comment-auth.guard.ts, api/src/users/users.controller.spec.ts, api/src/users/users.controller.ts, api/test/auth.e2e-spec.ts
Closes #104
This PR changes field names in the schema (because they were designed [by a moron](https://c.tenor.com/Q_6JIVo5V3kAAAAC/tenor.gif)) and naturally requires all references in the backend to change.
This PR will require a frontend rework as well. By someone who is both talented and generous.
Pull, Switch, up db/api, `npm run db:migrate`, `npm run db:generate`
Test the project as normal doing a full e2e runthrough. I did it on my end and everything seems okay but not sure. Your postman bodies will need to change naturally.
I'll provide an updated postman file.
=> Issue-104: Map each schema property suchthat it's camel case

web/src/components/List/ListGrid/ListCard.tsx, web/src/components/List/ListGrid/ListGrid.tsx, web/src/components/List/MovieListCard/MovieActions.tsx, web/src/components/List/MovieListCard/MovieListCard.tsx, web/src/components/List/MovieListGrid/MovieListContainer.tsx, web/src/components/List/MovieListGrid/MovieListGrid.tsx, web/src/components/Login/LoginCard.tsx, web/src/context/lists.context.tsx, web/src/types.ts
Closes #124 
After backend changes in PR #117, the frontend DTOs do not match the backend. This PR fixes this by updating the DTOs to match and correcting usage in pages and components
Verify all frontend functionality from Vercel preview, specifically adding movies to a list and saving the list.
=> Issue-124: Update frontend to match backend schema updates

api/prisma/migrations/20231103142249_/migration.sql, api/prisma/schema.prisma, api/src/lists/daos/list.dao.ts, api/src/lists/lists.controller.ts, api/src/lists/lists.service.ts, api/src/users/users.controller.spec.ts
Closes #41
This PR adds the ability to mark a specific movie as "watched" -> `PATCH {{BASE_URL}}/lists/updateWatchedStatus`:
```ts
{
"movieId": "{{movieId}}" // ex: 4fa587ce-4302-4152-8b2e-51bdfb994eba
}
```
Nothing is being marked as watched in the backend. Specifically, the user table now has a many-to-many relationship with the movie table. Many movies can be associated with many users. This relationship means we don't need for an intermediate table to handle a watched status: if the movie is marked as watched it is watched, if not, it is not. 
Additionally, I've changed the get list sharees endpoint (`GET {{BASE_URL}}/lists/sharees?listId={{listId}}`) to return the following information now:
```json
[
{
"username": "chris",
"email": "chris@chris.chris",
"creator": false,
"watched": [ …
```
=> Issue-41: Mark a movie on a list as watched

api/src/email/email.service.ts, api/src/lists/lists.controller.ts, api/src/lists/lists.service.ts
Closes #127
This PR adds an email to be sent out upon a new comment on a list (_by someone who isn't the list creator commenting on their own list_).
It also tweaks the email service to CC the list creator when sending out the list sharing email, and it adds the list name to the email instead of the list id.
There's not much that can be tested locally here unfortunately.
=> Issue-127: Tweak email service (and add list comment email)

api/src/users/daos/user.dao.ts, api/src/users/export/export.controller.spec.ts, api/src/users/export/export.controller.ts, api/src/users/export/export.module.ts, api/src/users/export/export.service.spec.ts, api/src/users/export/export.service.ts, api/src/users/users.module.ts, api/src/users/users.service.ts
Closes #130
This PR adds the ability for users to export their own data (in json format). The data being returned is marked as a response attachment- so I think the browser will automatically try to download it when requested?
Run the new route (`GET {{BASE_URL}}/export/`) on a user with lists and movies watched. Postman should respond with the data being returned.
=> Issue-130: Implement user export

web/src/app/dashboard/friends/page.tsx, web/src/components/Friends/FriendAction.tsx, web/src/components/Friends/FriendsAdd.tsx, web/src/components/Friends/FriendsCard.tsx, web/src/components/Friends/FriendsContainer.tsx, web/src/components/Friends/FriendsMain.tsx, web/src/types.ts, web/src/utils/cinesync-api/fetch-user.ts
closes #53 
This PR adds a new page (friends).
On the friends page the user can:
- add new friends
- cancel existing friend requests
- remove existing friends
- reject pending friend requests
- npm i
- npm run dev
- navigate to the friends page from the header menu
=> Issue-53: Implement a friend management page

api/src/lists/daos/list.dao.ts, api/src/lists/guards/list-private.guard.ts, api/src/lists/guards/list.guard.ts, api/src/lists/guards/share-list.guard.ts, api/src/lists/lists.controller.ts, api/src/lists/lists.module.ts, api/src/lists/lists.service.ts, api/src/users/auth/passport/jwt.strategy.ts, api/src/users/avatar/avatar.module.ts, api/src/users/avatar/avatar.service.spec.ts, api/src/users/avatar/avatar.service.ts, api/src/users/daos/user.dao.ts, api/src/users/export/export.module.ts, api/src/users/guards/comment-auth.guard.ts, api/src/users/users.controller.spec.ts, api/src/users/users.controller.ts, api/src/users/users.module.ts, api/src/users/users.service.ts
Closes #47, #88, #158, #128
This PR changes the following:
1. Rename various services/daos/guards
2. Allow admins to delete any list
3. Disallow users from unsharing themselves from their own list
4. Disallow sharees from unsharing the list creator from their own list
5. Disallow sharees from altering list privacy
I know this is a lot but I wanted to get it all in one instead of several because they're all relatively small changes and making and having five PRs reviewed seemed exhausting.
The first two can't really be tested aside from changing your user status in your local DB to admin and attempting to delete a list that is not yours. The last three can be tested based on the description above.
=> Various API fixes (see desc)

api/src/lists/daos/list.dao.ts, web/src/components/List/ListGrid/ListCard.tsx, web/src/components/List/MovieListGrid/MovieListComments/MovieListComment.tsx, web/src/components/List/MovieListGrid/MovieListComments/MovieListCommentAdd.tsx, web/src/components/List/MovieListGrid/MovieListComments/MovieListCommentEdit.tsx, web/src/components/List/MovieListGrid/MovieListComments/MovieListComments.tsx, web/src/components/List/MovieListGrid/MovieListContainer.tsx, web/src/context/lists.context.tsx, web/src/types.ts, web/src/utils/cinesync-api/fetch-list.ts, web/src/utils/cinesync-api/fetch-user.ts, web/src/utils/cinesync-api/fetch.ts
Closes #143 
This PR adds list comment support to the frontend. Movie list pages will contain a comments section below the list contents. These comments will have:
- User Avatar (these are only fetched once per unique user even if they have multiple comments)
- Username
- Date/Time
- Whether the comment has been edited
- Comment text
- Editor functionality
- Delete comment button
An add comment input will appear at the top of the section, and any new comments will appear directly below (sorted descending by creation date).
The comment list will appear as a trimmed section (3 comments), providing a "Load More" button to expand the section to all comments.
The user context is used to ensure edit/delete can only be done by the user that created the comment.
Example from user 1
Example from …
=> Issue-143: Add list comment support on frontend

web/src/components/List/ListActions.tsx, web/src/components/List/ListGrid/ListCard.tsx, web/src/components/List/ListGrid/ListCreator.tsx, web/src/components/List/ListGrid/ListGrid.tsx, web/src/components/List/ListGrid/ListShareeAvatars.tsx, web/src/components/List/ListShareModal.tsx, web/src/types.ts
closes #77 and #132
This PR adds a FE component that shows avatars that have shared a list on the bottom of the list card component.
It also adds a creator avatar next to the list name.
run as normal, create a list, share with users.
=> Issue-77: Show sharee avatars on `List` component

web/src/components/List/MovieListGrid/MovieListComments/MovieListCommentEdit.tsx
Fixes #166 
This PR fixes the display and editing of multi-line movie list comments.
- Using deployment preview, add a comment containing newline characters to a movie list (press enter to add newlines).
- Verify the comment displays as a multi-line comment.
- Click on the edit comment button.
- Verify the comment displays as multi-line in the edit text area.
- Submit the edited comment.
- Verify the update comment is displayed as multi-line.
=> Issue-166: Comments with newlines not being rendered on the frontend

web/src/components/UserProfile/ExportUserData.tsx, web/src/components/UserProfile/ProfileTop.tsx, web/src/types.ts, web/src/utils/cinesync-api/fetch-user.ts
closes #147 
PR adds exporting of user data functionality, downloads a json file.
From PR preview go to user page and click the button beside user profile.
=> feat(web): add data export button to user page

web/src/components/Friends/FriendsCard.tsx, web/src/components/List/ListGrid/ListCreator.tsx, web/src/components/List/ListGrid/ListShareeAvatars.tsx, web/src/context/user.context.tsx
closes #151 
Refactored the avatar fetch functions that were duplicated across the entire app and now using the utils function for getting an avatar for the user and for a specific user.
nothing to test, just refactor. Can look at preview.
=> Issue-151: change avatar callbacks to use utils functions

web/src/components/List/ListActions.tsx, web/src/components/List/ListGrid/ListCard.tsx, web/src/components/List/MovieListGrid/MovieListComments/MovieListCommentEdit.tsx, web/src/components/List/MovieListGrid/MovieListContainer.tsx, web/src/components/List/MovieListGrid/MovieListTitle.tsx
Fixes #136 
This PR adds guards to prevent sharees from making changes to movie lists (since they are not the creator). The following is prevented:
- List deletion
- List title editing
- List sharing
- List privacy toggle
Lists Page:
- Creator 
- Sharee
Movie List Page:
- Creator
- Sharee
Using Vercel deployment, log in as two distinct users. Share lists between these users and check on the main page and a list page that the list options (edit/delete/share/privacy) are hidden when you are a sharee of a list.
=> Issue-136: Disallow sharees (non-creators) from sharing/deleting a movie list
